Cleaned-up some dangling messiness.
Also, added a note regarding a "surprising" dependency that eventually needs
to be addressed (which I have seen occasionally breaks the CMake build):
packages/nidr/../ampl/asl.h:28:51: error: arith.h: No such file or dir

If any developer encounters the build error noted above, please let me know,
and I will move the issue higher on my ToDo list.



git-svn-id: svn+ssh://software.sandia.gov/svn/dakota/core/trunk@314 aa0779c3-6ec2-4b84-a212-a405c134cd8d